version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: "terminaltask-mac"
    main: ./cmd/terminaltask
    binary: terminaltask
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.buildDate={{.Date}}

  - id: "terminaltask-linux"
    main: ./cmd/terminaltask
    binary: terminaltask
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.buildDate={{.Date}}

archives:
  - id: terminaltask-mac-archive
    builds:
      - terminaltask-mac
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

  - id: terminaltask-linux-archive
    builds:
      - terminaltask-linux
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

changelog:
  use: github

release:
  github:
    owner: "jacobdanielrose"
    name: "terminaltask"

homebrew_casks:
  - name: terminaltask

    # Where the cask will live (your tap repo)
    repository:
      owner: jacobdanielrose
      name: homebrew-tap # create this repo once on GitHub

    # Use the macOS build to back this cask
    ids:
      - terminaltask-mac-archive

    description: "TUI task manager built with Bubble Tea"
    homepage: "https://github.com/jacobdanielrose/terminaltask"

    # Optional: author of the commits into the tap repo
    commit_author:
      name: "Jacob Rose"
      email: "you@example.com" # change this
