version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: "terminaltask-mac"
    main: ./cmd/terminaltask
    binary: terminaltask
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.buildDate={{.Date}}

  - id: "terminaltask-linux"
    main: ./cmd/terminaltask
    binary: terminaltask
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.buildDate={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

changelog:
  use: github

release:
  github:
    owner: "jacobdanielrose"
    name: "terminaltask"

brews:
  - name: terminaltask

    # Where the formula will live (your tap repo)
    repository:
      owner: jacobdanielrose
      name: terminaltask

    # Use the macOS build for the formula
    ids:
      - terminaltask-mac

    description: "TUI task manager built with Bubble Tea"
    homepage: "https://github.com/jacobdanielrose/terminaltask"

    # How Homebrew installs your binary from the tarball
    install: |
      bin.install "terminaltask"

    # Basic Homebrew test
    test: |
      system "#{bin}/terminaltask", "--version"

    commit_author:
      name: "Jacob Rose"
      email: "you@example.com" # update
